cpp_compiler := $(ELF_GCC)
asm_compiler := 

int_dir := $(int_dir)/libsimpleos2
bin_dir := $(bin_dir)/libsimpleos2

includes := 

compile_flags := -g -ffreestanding -fno-stack-protector -fno-exceptions

out_file := libsimpleos2.a

include ../makeinclude/cpp_static.mk