cpp_compiler := $(ELF_GCC)
asm_compiler := 

int_dir := $(int_dir)/libc
bin_dir := $(bin_dir)/libc

includes := 

compile_flags := -g -ffreestanding -fno-stack-protector -fno-exceptions

out_file := libc.a

include ../makeinclude/cpp_static.mk